export const GET_DETAIL_HOMESTAY_REQUEST = 'GET_DETAIL_HOMESTAY_REQUEST'
export const GET_DETAIL_HOMESTAY_SUCCESS = 'GET_DETAIL_HOMESTAY_SUCCESS'
export const GET_DETAIL_HOMESTAY_FAILURE = 'GET_DETAIL_HOMESTAY_FAILURE'