export const GET_DETAIL_HOMESTAY_REQUEST = 'GET_DETAIL_HOMESTAY_REQUEST'
export const GET_DETAIL_HOMESTAY_SUCCESS = 'GET_DETAIL_HOMESTAY_SUCCESS'
export const GET_DETAIL_HOMESTAY_FAILURE = 'GET_DETAIL_HOMESTAY_FAILURE'

export const RATE_DETAIL_HOMESTAY_REQUEST = 'RATE_DETAIL_HOMESTAY_REQUEST'
export const RATE_DETAIL_HOMESTAY_SUCCESS = 'RATE_DETAIL_HOMESTAY_SUCCESS'
export const RATE_DETAIL_HOMESTAY_FAILURE = 'RATE_DETAIL_HOMESTAY_FAILURE'

export const GET_SIMILAR_HOMESTAY_REQUEST = 'GET_SIMILAR_HOMESTAY_REQUEST'
export const GET_SIMILAR_HOMESTAY_SUCCESS = 'GET_SIMILAR_HOMESTAY_SUCCESS'
export const GET_SIMIALR_HOMESTAY_FAILURE = 'GET_SIMIALR_HOMESTAY_FAILURE'

export const UPDATE_COUNT_SHARES = 'UPDATE_COUNT_SHARES'


