export const GET_BEST_HOMESTAY_REQUEST = 'GET_BEST_HOMESTAY_REQUEST'
export const GET_BEST_HOMESTAY_SUCCESS = 'GET_BEST_HOMESTAY_SUCCESS'
export const GET_BEST_HOMESTAY_FAILURE = 'GET_BEST_HOMESTAY_FAILURE'

export const GET_BEST_TRAVELLER_REQUEST = 'GET_BEST_TRAVELLER_REQUEST'
export const GET_BEST_TRAVELLER_SUCCESS = 'GET_BEST_TRAVELLER_SUCCESS'
export const GET_BEST_TRAVELLER_FAILURE = 'GET_BEST_TRAVELLER_FAILURE'