export const GET_HOMESTAY_REQUEST = 'GET_HOMESTAY_REQUEST'
export const GET_HOMESTAY_SUCCESS = 'GET_HOMESTAY_SUCCESS'
export const GET_HOMESTAY_FAILURE = 'GET_HOMESTAY_FAILURE'

export const CREATE_HOMESTAY_REQUEST = 'CREATE_HOMESTAY_REQUEST'
export const CREATE_HOMESTAY_SUCCESS = 'CREATE_HOMESTAY_SUCCESS'
export const CREATE_HOMESTAY_FAILURE = 'CREATE_HOMESTAY_FAILURE'


export const CREATE_HOMESTAY_SIMILARITY_REQUEST = 'CREATE_HOMESTAY_SIMILARITY_REQUEST'
export const CREATE_HOMESTAY_SIMILARITY_SUCCESS = 'CREATE_HOMESTAY_SIMILARITY_SUCCESS'
export const CREATE_HOMESTAY_SIMILARITY_FAILURE = 'CREATE_HOMESTAY_SIMILARITY_FAILURE'

export const UPDATE_HOMESTAY_SIMILARITY_REQUEST = 'UPDATE_HOMESTAY_SIMILARITY_REQUEST'
export const UPDATE_HOMESTAY_SIMILARITY_SUCCESS = 'UPDATE_HOMESTAY_SIMILARITY_SUCCESS'
export const UPDATE_HOMESTAY_SIMILARITY_FAILURE = 'UPDATE_HOMESTAY_SIMILARITY_FAILURE'

export const DELETE_HOMESTAY_SIMILARITY_REQUEST = 'DELETE_HOMESTAY_SIMILARITY_REQUEST'
export const DELETE_HOMESTAY_SIMILARITY_SUCCESS = 'DELETE_HOMESTAY_SIMILARITY_SUCCESS'
export const DELETE_HOMESTAY_SIMILARITY_FAILURE = 'DELETE_HOMESTAY_SIMILARITY_FAILURE'

export const ADMIN_APPROVE_HOMESTAY_REQUEST = 'ADMIN_APPROVE_HOMESTAY_REQUEST'
export const ADMIN_APPROVE_HOMESTAY_SUCCESS = 'ADMIN_APPROVE_HOMESTAY_SUCCESS'
export const ADMIN_APPROVE_HOMESTAY_FAILURE = 'ADMIN_APPROVE_HOMESTAY_FAILURE'

export const ADMIN_DELETE_HOMESTAY_REQUEST = 'ADMIN_DELETE_HOMESTAY_REQUEST'
export const ADMIN_DELETE_HOMESTAY_SUCCESS = 'ADMIN_DELETE_HOMESTAY_SUCCESS'
export const ADMIN_DELETE_HOMESTAY_FAILURE = 'ADMIN_DELETE_HOMESTAY_FAILURE'
