export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE'

export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE'

export const GET_LIST_PROFILE_REQUEST = 'GET_LIST_PROFILE_REQUEST'
export const GET_LIST_PROFILE_SUCCESS = 'GET_LIST_PROFILE_SUCCESS'
export const GET_LIST_PROFILE_FAILURE = 'GET_LIST_PROFILE_FAILURE'

// export const CREATE_HOMESTAY_REQUEST = 'CREATE_HOMESTAY_REQUEST'
// export const CREATE_HOMESTAY_SUCCESS = 'CREATE_HOMESTAY_SUCCESS'
// export const CREATE_HOMESTAY_FAILURE = 'CREATE_HOMESTAY_FAILURE'

// export const CREATE_HOMESTAY_SIMILARITY_REQUEST = 'CREATE_HOMESTAY_SIMILARITY_REQUEST'
// export const CREATE_HOMESTAY_SIMILARITY_SUCCESS = 'CREATE_HOMESTAY_SIMILARITY_SUCCESS'
// export const CREATE_HOMESTAY_SIMILARITY_FAILURE = 'CREATE_HOMESTAY_SIMILARITY_FAILURE'
