export const GET_MYRATE_REQUEST = 'GET_MYRATE_REQUEST'
export const GET_MYRATE_SUCCESS = 'GET_MYRATE_SUCCESS'
export const GET_MYRATE_FAILURE = 'GET_MYRATE_FAILURE'

export const UPDATE_COUNT_RATE = 'UPDATE_COUNT_RATE'


